[project]
name = "declutter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-ollama>=1.0.1",
    "ollama>=0.6.1",
    "pillow>=12.0.0",
    "watchdog>=6.0.0",
]
